baseurl = "http://bnjmn.info/principalgroup/"
languageCode = "en-us"
title = "Principal Group"
theme = "creative"
googleAnalytics = "UA-89385252-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "PrincipalGroup"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			#portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "EB-5 Investment Services"
		subtitle   = "Changing Communities"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Transparent and Efficient"
		description = "We have helped hundreds of investors through the EB-5 process and are reinventing the EB-5 process. We can help if you are just getting started or if you want the full investment services."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-usd"
            title = "Fund your project"
            description = "We fund your project"
	  
        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Show Off Your Home"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
            icon = "fa-gavel"
            title = "Project Submission"
            description = "Flat-fee project submission that includes immigration, security, economics report and business plan"

        [[params.services.list]]
            icon = "fa-rocket"
            title = "Start Your Own Regional Center" 
            description = "We help you do it yourself"
	    link = "//github.com/bnjmn/principalgroup.git"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the PrincipalGroup Package!"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/bnjmn/principalgroup.git"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "786-760-0433"
		email = "hello@principalgroup.org"
		address = "842 Park Ave., Rm 5, Baltimore MD"
	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""

